-- BBC Learning English Database Schema
-- Generated for PET/FCE AI English Learning Platform
-- Date: 2026-02-16

-- ============================================================
-- Core Course Structure
-- ============================================================

-- Course levels (intermediate, lower-intermediate)
CREATE TABLE IF NOT EXISTS levels (
    level_id TEXT PRIMARY KEY,  -- 'intermediate', 'lower-intermediate'
    title TEXT NOT NULL,
    description TEXT,
    total_units INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Units within each level
CREATE TABLE IF NOT EXISTS units (
    unit_id INTEGER PRIMARY KEY AUTOINCREMENT,
    level_id TEXT NOT NULL,
    unit_number INTEGER NOT NULL,
    title TEXT,
    description TEXT,
    url TEXT,
    downloads_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (level_id) REFERENCES levels(level_id) ON DELETE CASCADE,
    UNIQUE(level_id, unit_number)
);

-- Sessions within each unit
CREATE TABLE IF NOT EXISTS sessions (
    session_id INTEGER PRIMARY KEY AUTOINCREMENT,
    unit_id INTEGER NOT NULL,
    session_number INTEGER NOT NULL,
    type TEXT,  -- 'vocabulary', 'grammar', 'reading', 'listening', 'drama', 'quiz', 'unknown'
    title TEXT,
    url TEXT,
    audio_url TEXT,
    transcript_html TEXT,
    transcript_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (unit_id) REFERENCES units(unit_id) ON DELETE CASCADE,
    UNIQUE(unit_id, session_number)
);

-- Activities within each session
CREATE TABLE IF NOT EXISTS activities (
    activity_id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL,
    activity_number INTEGER NOT NULL,
    title TEXT,
    instruction TEXT,
    url TEXT,
    content_html TEXT,
    content_text TEXT,
    has_audio BOOLEAN DEFAULT 0,
    audio_url TEXT,
    has_transcript BOOLEAN DEFAULT 0,
    transcript_html TEXT,
    transcript_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
    UNIQUE(session_id, activity_number)
);

-- ============================================================
-- Vocabulary Tables
-- ============================================================

-- Session-level vocabulary (from sidebar)
CREATE TABLE IF NOT EXISTS session_vocabulary (
    vocab_id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL,
    section_title TEXT,      -- e.g., "Compound adjectives with hyphens"
    word TEXT,               -- vocabulary word or example phrase
    definition TEXT,         -- English definition
    rule TEXT,               -- grammar/word-formation rule (for grammar sessions)
    is_example BOOLEAN DEFAULT 0,  -- whether this is an example of a rule
    sort_order INTEGER,      -- order in the page
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

-- Unit-level vocabulary (full vocabulary reference)
CREATE TABLE IF NOT EXISTS unit_vocabulary (
    vocab_id INTEGER PRIMARY KEY AUTOINCREMENT,
    unit_id INTEGER NOT NULL,
    word TEXT NOT NULL,
    definition TEXT,
    source_session INTEGER,  -- source session number (nullable)
    sort_order INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (unit_id) REFERENCES units(unit_id) ON DELETE CASCADE
);

-- Bold words extracted from content
CREATE TABLE IF NOT EXISTS bold_words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    activity_id INTEGER NOT NULL,
    word TEXT NOT NULL,
    context_sentence TEXT,   -- sentence containing the word
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (activity_id) REFERENCES activities(activity_id) ON DELETE CASCADE
);

-- ============================================================
-- Download Resources
-- ============================================================

-- Downloadable resources (audio, transcripts)
CREATE TABLE IF NOT EXISTS downloads (
    download_id INTEGER PRIMARY KEY AUTOINCREMENT,
    unit_id INTEGER NOT NULL,
    resource_title TEXT,
    session_number INTEGER,
    activity_number INTEGER,
    audio_url TEXT,
    audio_size TEXT,
    transcript_url TEXT,
    local_audio_path TEXT,   -- local file path after download
    local_transcript_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (unit_id) REFERENCES units(unit_id) ON DELETE CASCADE
);

-- ============================================================
-- LLM-Generated Content (Gemini)
-- ============================================================

-- Flashcards generated by Gemini
CREATE TABLE IF NOT EXISTS flashcards (
    card_id INTEGER PRIMARY KEY AUTOINCREMENT,
    vocab_id INTEGER,        -- reference to session_vocabulary or unit_vocabulary
    source_table TEXT,       -- 'session_vocabulary' or 'unit_vocabulary'
    word TEXT NOT NULL,
    definition_en TEXT,      -- original English definition
    definition_cn TEXT,      -- Chinese definition (Gemini-generated)
    example_en TEXT,         -- English example sentence (Gemini-generated)
    example_cn TEXT,         -- Chinese translation (Gemini-generated)
    difficulty TEXT,         -- 'easy', 'medium', 'hard'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vocab_id) REFERENCES session_vocabulary(vocab_id) ON DELETE SET NULL
);

-- Exercises generated by Gemini
CREATE TABLE IF NOT EXISTS exercises (
    exercise_id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER,
    exercise_type TEXT NOT NULL,  -- PET question types (see enum below)
    question TEXT NOT NULL,
    options TEXT,            -- JSON array: ["A. ...", "B. ...", "C. ...", "D. ..."]
    correct_answer TEXT,
    explanation TEXT,        -- Gemini-generated explanation
    difficulty TEXT,         -- 'easy', 'medium', 'hard'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

-- ============================================================
-- User Progress Tracking
-- ============================================================

-- User progress on activities
CREATE TABLE IF NOT EXISTS user_progress (
    progress_id INTEGER PRIMARY KEY AUTOINCREMENT,
    activity_id INTEGER NOT NULL,
    completed BOOLEAN DEFAULT 0,
    completed_at TIMESTAMP,
    time_spent INTEGER,      -- seconds spent on activity
    FOREIGN KEY (activity_id) REFERENCES activities(activity_id) ON DELETE CASCADE,
    UNIQUE(activity_id)
);

-- Flashcard learning progress (SM-2 algorithm)
CREATE TABLE IF NOT EXISTS flashcard_progress (
    progress_id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_id INTEGER NOT NULL,
    easiness_factor REAL DEFAULT 2.5,  -- SM-2 EF
    repetitions INTEGER DEFAULT 0,
    interval INTEGER DEFAULT 0,        -- days until next review
    next_review_date DATE,
    last_reviewed_at TIMESTAMP,
    FOREIGN KEY (card_id) REFERENCES flashcards(card_id) ON DELETE CASCADE,
    UNIQUE(card_id)
);

-- Exercise attempt records
CREATE TABLE IF NOT EXISTS exercise_attempts (
    attempt_id INTEGER PRIMARY KEY AUTOINCREMENT,
    exercise_id INTEGER NOT NULL,
    user_answer TEXT,
    is_correct BOOLEAN,
    attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (exercise_id) REFERENCES exercises(exercise_id) ON DELETE CASCADE
);

-- ============================================================
-- Indexes for Performance
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_units_level ON units(level_id);
CREATE INDEX IF NOT EXISTS idx_sessions_unit ON sessions(unit_id);
CREATE INDEX IF NOT EXISTS idx_activities_session ON activities(session_id);
CREATE INDEX IF NOT EXISTS idx_session_vocab_session ON session_vocabulary(session_id);
CREATE INDEX IF NOT EXISTS idx_unit_vocab_unit ON unit_vocabulary(unit_id);
CREATE INDEX IF NOT EXISTS idx_bold_words_activity ON bold_words(activity_id);
CREATE INDEX IF NOT EXISTS idx_downloads_unit ON downloads(unit_id);
CREATE INDEX IF NOT EXISTS idx_flashcards_vocab ON flashcards(vocab_id);
CREATE INDEX IF NOT EXISTS idx_exercises_session ON exercises(session_id);
CREATE INDEX IF NOT EXISTS idx_flashcard_progress_next_review ON flashcard_progress(next_review_date);

-- ============================================================
-- Exercise Type Enumeration (for reference)
-- ============================================================

-- Reading exercises:
--   - reading_multiple_choice
--   - reading_gapped_text
--   - reading_matching
--
-- Listening exercises:
--   - listening_multiple_choice
--   - listening_gap_fill
--
-- Vocabulary exercises:
--   - vocab_definition_match
--   - vocab_fill_in_blank
--   - vocab_word_formation
--
-- Grammar exercises:
--   - grammar_fill_in_blank
--   - grammar_error_correction
--   - grammar_sentence_transform

-- ============================================================
-- Initial Data
-- ============================================================

INSERT OR IGNORE INTO levels (level_id, title, description) VALUES
    ('intermediate', 'Intermediate', 'BBC Learning English Intermediate Course (~11 units)'),
    ('lower-intermediate', 'Lower Intermediate', 'BBC Learning English Lower Intermediate Course (~30 units)');
